In [1]:
import pandas as pd

In [18]:
weather_data = pd.read_csv("environmental_data.csv")
weather_data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

## Data Understanding

In [4]:
weather_data.shape

(158, 10)

In [5]:
weather_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [6]:
weather_data[weather_data.duplicated]

Empty DataFrame
Columns: [Unnamed: 0, Ozone, Solar.R, Wind, Temp C, Month, Day, Year, Temp, Weather]
Index: []

In [7]:
weather_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [8]:
weather_data.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

In [10]:
weather_data.describe(include="all")

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [11]:
weather_data["Weather"].unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [12]:
weather_data["Weather"].value_counts()

Weather
S     59
C     49
PS    47
Name: count, dtype: int64

In [13]:
weather_data["Weather"].value_counts(dropna=False)

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

In [22]:
weather_data = pd.read_csv("environmental_data.csv")
weather_data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

## Data Perparation

In [23]:
weather_data.drop(columns=["Temp C","Unnamed: 0"],axis=1,inplace=True)

In [24]:
weather_data.columns

Index(['Ozone', 'Solar.R', 'Wind', 'Month', 'Day', 'Year', 'Temp', 'Weather'], dtype='object')

In [27]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [25]:
weather_data.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [29]:
# weather_data["Ozone"] = weather_data["Ozone"].fillna(weather_data["Ozone"].mean(), inplace=True)
# weather_data["Ozone"].dropna(axis=0, inplace=True)

del weather_data["Ozone"]

In [30]:
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4        NaN  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [31]:
weather_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [32]:
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4        NaN  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [34]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [38]:
weather_data.groupby("Weather")["Solar.R"].mean().round(2)

Weather
C     192.39
PS    174.35
S     193.33
Name: Solar.R, dtype: float64

In [39]:
weather_data["Solar.R"] =  weather_data.groupby("Weather")["Solar.R"].transform(lambda x:x.fillna(x.mean().round()))

In [41]:
weather_data[ weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [49]:
weather_data.dropna(axis=0,inplace=True)

In [50]:
weather_data[ weather_data["Solar.R"].isna()]

Empty DataFrame
Columns: [Solar.R, Wind, Month, Day, Year, Temp, Weather]
Index: []

In [51]:
weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [52]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [53]:
weather_data["Month"].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [54]:
weather_data["Month"].replace(to_replace='May',value =5, inplace=True)

/var/folders/hd/sgyrmsjj6fx1h2p_tyfv8r_c0000gn/T/ipykernel_29754/244411972.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  weather_data["Month"].replace(to_replace='May',value =5, inplace=True)

In [55]:
weather_data["Month"].unique()

array(['5', 5, '6', '7', '8', '9'], dtype=object)

In [57]:
weather_data.head(30)

    Solar.R  Wind Month  Day  Year  Temp Weather
0     190.0   7.4     5    1  2010    67       S
1     118.0   8.0     5    2  2010    72       C
2     149.0  12.6     5    3  2010    74      PS
3     313.0  11.5     5    4  2010    62       S
4     193.0  14.3     5    5  2010    56       S
5     192.0  14.9     5    6  2010    66       C
6     299.0   8.6     5    7  2010    65      PS
7      99.0  13.8     5    8  2010    59       C
8      19.0  20.1     5    9  2010    61      PS
9     194.0   8.6     5   10  2010    69       S
10    192.0   6.9     5   11  2010    74       C
11    256.0   9.7     5   12  2010    69      PS
12    290.0   9.2     5   13  2010    66       S
13    274.0  10.9     5   14  2010    68       S
14     65.0  13.2     5   15  2010    58       C
15    334.0  11.5     5   16  2010    64       S
16    307.0  12.0     5   17  2010    66       S
17     78.0  18.4     5   18  2010    57       C
18    322.0  11.5     5   19  2010    68      PS
19     44.0   9.7     5   20  2010    62       S
20      8.0   9.7     5   21  2010    59       S
21    320.0  16.6     5   22  2010    73       C
22     25.0   9.7     5   23  2010    61      PS
23     92.0  12.0     5   24  2010    61       C
24     66.0  16.6     5   25  2010    57      PS
25    266.0  14.9     5   26  2010    58       C
26    174.0   8.0     5   27  2010    57      PS
27     13.0  12.0     5   28  2010    67       S
28    252.0  14.9     5   29  2010    81       S
29    223.0   5.7     5   30  2010    79       C

In [58]:
weather_data["Month"] = weather_data["Month"].astype('int')

In [59]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [60]:
weather_data["Weather"].unique

<bound method Series.unique of 0       S
1       C
2      PS
3       S
4       S
       ..
153     C
154    PS
155     S
156     S
157     C
Name: Weather, Length: 155, dtype: object>

In [61]:
weather_data["Weather"].value_counts()

Weather
S     59
C     49
PS    47
Name: count, dtype: int64

## Stage 2

## Data Transformation

* If the data is CONTINUOUS  --> Standard Scalar, MinMaxScalar, Robust Scalar
* If the data is DISCRETE --> Label Encoder , One HOT encoder

In [68]:
weather_data_copy_01 = weather_data.copy()
weather_data_copy_01

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [69]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
weather_data_copy_01["Weather"] = le_encoder.fit_transform(weather_data_copy_01["Weather"])

In [71]:
weather_data_copy_01.head()

   Solar.R  Wind  Month  Day  Year  Temp  Weather
0    190.0   7.4      5    1  2010    67        2
1    118.0   8.0      5    2  2010    72        0
2    149.0  12.6      5    3  2010    74        1
3    313.0  11.5      5    4  2010    62        2
4    193.0  14.3      5    5  2010    56        2

## One Hot Encoder

* pd.get_dummies
* sklearn - OneHotencoder

In [75]:
weather_data_copy_02 = weather_data.copy()
weather_data_copy_02

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [76]:
pd.get_dummies(data=weather_data_copy_02, columns=["Weather"], dtype=int)

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

In [93]:
weather_data_copy_03 = weather_data.copy()
weather_data_copy_03

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [94]:
from sklearn.preprocessing import OneHotEncoder

one_hot = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
# one_hot = OneHotEncoder()

In [95]:
encoded_weather = one_hot.fit_transform(weather_data_copy_03[["Weather"]])
encoded_weather

weather_data_copy_03 = weather_data_copy_03.drop(columns=["Weather"]).join(encoded_weather)

In [96]:
weather_data_copy_03.head()

   Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0    190.0   7.4      5    1  2010    67        0.0         0.0        1.0
1    118.0   8.0      5    2  2010    72        1.0         0.0        0.0
2    149.0  12.6      5    3  2010    74        0.0         1.0        0.0
3    313.0  11.5      5    4  2010    62        0.0         0.0        1.0
4    193.0  14.3      5    5  2010    56        0.0         0.0        1.0